### ISSUE TITLE
Light dot in top-left corner

### ISSUE THREAD

**Issue by Gei-1** [Lyall/DDDAFix#2]
Hey and thanks for this, made the game so much better on Steam Deck.

In-game, only during normal play, a light-blue dot is present in the top-left corner. It dissapears during cutscenes, when in menu or even when talking to characters. It also disappears if you disable the mini-map in the menu.

![20240427_211732](https://github.com/Lyall/DDDAFix/assets/102943357/0dad6977-2476-42a9-8386-ab5262f8aaa8)

**Comment by Lyall** [comment]
So after doing a bit of investigating it seems to be a bit of extra overflow from the UI. Basically it was always there, it's just now that with a proper <16:9 solution we can see this extra bit of UI. Unfortunately I'm not sure where to start on trying to address this. Tools like RenderDoc and NSight are off the table sadly so I think possibly the best solution might be to try and offer a stretched UI. That minor stretching from 16:9 to 16:10 on the Steam Deck wouldn't be too bad.

**Comment by Lyall** [comment]
Okay I've managed to isolate the UI element and resizing it doesn't appear to affect anything (I think?). Only problem is now that it's 24x24 and I can't find anything particularly unique to check for.

![DDDA_2024_05_02_08_34_43_978](https://github.com/Lyall/DDDAFix/assets/695941/9b449fac-2aae-4a37-aa40-b87dc61eb37b)

**Comment by Lyall** [comment]
![DDDA_2024_05_02_08_58_49_942](https://github.com/Lyall/DDDAFix/assets/695941/572e7855-d531-4cdf-b7d1-6ba21337d5d7)

Alright I think I've got it. Can you try this test build and let me know if it works for you?

[DDDAFix_v0.9.1.zip](https://github.com/Lyall/DDDAFix/files/15185400/DDDAFix_v0.9.1.zip)

**Comment by Gei-1** [comment]
Thank you for looking into this. Tested 0.9.1, the dot is gone and it seems everything else is still working fine.

**Comment by RyuSeisuke1992** [comment]
Thank you very much. I saw the point but it hadn't bothered me that much. With 0.9.1 it is now gone. Quick note: at 180 hours with the widescreen mod for the Steam deck, I only noticed a small visual discrepancy. Unfortunately I didn't take a screenshot of it. When you are on the map, the place names and the cursor flicker a little when you point to a place. Can you confirm this? Maybe I'll make a separate Ticket out of it?
